name: expectiminimax
version: 1.0.0-beta.0
description: Dart implementation of Expectiminimax
homepage: https://github.com/MichaelRFairhurst/entropy_debugging.dart
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  test: '^1.6.5'
  mockito: '^4.1.0'
  collection: ^1.17.0
  args: ^2.3.1
